# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='新闻分类')),
            ],
            options={
                'verbose_name': '新闻分类',
                'db_table': 'tb_category',
                'verbose_name_plural': '新闻分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞条数')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'tb_comment',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户与点赞评论的关联表',
                'db_table': 'tb_comment_like',
                'verbose_name_plural': '用户与点赞评论的关联表',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=256, verbose_name='新闻标题')),
                ('source', models.CharField(max_length=64, verbose_name='新闻来源')),
                ('digest', models.CharField(max_length=512, verbose_name='新闻摘要')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('clicks', models.IntegerField(default=0, verbose_name='浏览量')),
                ('index_image_url', models.CharField(max_length=256, verbose_name='图片路径')),
                ('status', models.IntegerField(default=0, verbose_name='当前审核状态')),
                ('reason', models.CharField(max_length=256, verbose_name='审核不通过理由')),
            ],
            options={
                'verbose_name': '新闻',
                'db_table': 'tb_news',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
